name: Daily Character Cron

on:
  schedule:
    - cron: "0 3 * * *" # 00:00 BRT
  workflow_dispatch:

jobs:
  trigger-daily-character:
    runs-on: ubuntu-latest
    steps:
      - name: Chamar API route
        run: |
          curl -f -X GET "https://localhost:3000/api/cron/daily-character" \
            -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}"